version: 2
  jobs:
    featureTests:
      docker:
      - image: circleci/openjdk:8-jdk
      working_directory: ~/repo
      environment:
        JVM_OPTS: -Xmx3200m
        TERM: dumb
      steps:
      - checkout
      - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "build.gradle" }}
      - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
           - ~/.gradle
      key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
    userAPITests:
      docker:
      - image: circleci/openjdk:8-jdk
      working_directory: ~/repo
      environment:
        JVM_OPTS: -Xmx3200m
        TERM: dumb
      steps:
      - checkout
      - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "build.gradle" }}
      - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths: |
          cd users-api
            ./gradlew test
      key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
  workflows:
    version: 2
    one_and_two:
      jobs:
      - userAPITests
      - featureTests


