version: 2
  jobs:
    featureTests:
      docker:
      - image: circleci/openjdk:8-jdk
      working_directory: ~/repo
      environment:
        JVM_OPTS: -Xmx3200m
        TERM: dumb
      steps:
      - checkout
      - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "build.gradle" }}
      - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
           - ~/.gradle
      key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew test
    userAPITests:
      docker:
      - image: circleci/openjdk:8-jdk
      working_directory: ~/repo
      environment:
        JVM_OPTS: -Xmx3200m
        TERM: dumb
      steps:
      - checkout
      - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "build.gradle" }}
      - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
           - ~/.gradle
      key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: |
        cd users-api
        ./gradlew test
  workflows:
    version: 2
    all-tests:
      jobs:
      - userAPITests
      - featureTests:
        -userAPITests


